export const POST_REQUEST_LOADING="POST_REQUEST_LOADING";
export const POST_REQUEST_SUCCESS="POST_REQUEST_SUCCESS";
export const POST_REQUEST_ERROR="POST_REQUEST_ERROR";

export const GET_ADMIN_DATA_REQUEST="GET_ADMIN_DATA_REQUEST";
export const GET_ADMIN_DATA_SUCCESS="GET_ADMIN_DATA_SUCCESS";
export const GET_ADMIN_DATA_ERROR="GET_ADMIN_DATA_ERROR";