

// actionType.js
export const types = {
    LOGIN_SET_USER_DATA: "LOGIN_SET_USER_DATA",
    LOGIN_GET_USER_DATA: "LOGIN_GET_USER_DATA",
    LOGIN_REMOVE_USER_DATA: "LOGIN_REMOVE_USER_DATA",
    ADD_USER_LOADING: "ADD_USER_LOADING",
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    ADD_USER_ERROR: "ADD_USER_ERROR",
    GET_USER_LOADING: "GET_USER_LOADING",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_ERROR: "GET_USER_ERROR",
    };